### PR TITLE
serializers: access values only if set

### PR DESCRIPTION
**Pull request by rekt-hard**
:heart: Thank you for your contribution!

### Description

Perform resource type vocabulary lookup only if resource type is set.
Parse dates only if they are set

### Checklist

Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:

- [ ] I'm aware of the [code of conduct](https://inveniordm.docs.cern.ch/contribute/code-of-conduct/).
- [ ] I've created [logical separate commits](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#commits) and followed the [commit message format](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#commit-message).
- [ ] I've added relevant test cases.
- [ ] I've added relevant documentation.
- [ ] I've marked [translation strings](https://inveniordm.docs.cern.ch/develop/howtos/i18n/) (for relevant code).
- [ ] I've followed the [CSS/JS](https://inveniordm.docs.cern.ch/develop/best-practices/css-js/) and [React](https://inveniordm.docs.cern.ch/develop/best-practices/react/) guidelines (for relevant code).
- [ ] I've followed the [web accessibility](https://inveniordm.docs.cern.ch/develop/best-practices/accessibility/) guidelines (for relevant code).
- [ ] I've followed the [user interface](https://inveniordm.docs.cern.ch/develop/best-practices/ui/) guidelines (for relevant code).
- [ ] I've identified the [copyright holder(s)](https://inveniordm.docs.cern.ch/contribute/copyright-policy/) and updated copyright headers for touched files (>15 lines contributions).
- [ ] I've NOT included third-party code (copy/pasted source code or new dependencies).

**Third-party code**

If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).

**Reminder**

By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:

1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license your contribution under the current repository’s license.

### CODE REVIEW

**Comment by utnapischtim** [comment]
is this a bugfix or a feature?

**Comment by rekt-hard** [comment]
Bugfix. It is only about making sure the values exist before performing a lookup or trying to parse it.

For example, performing the following steps will lead to an error:
- Create a new draft
- Remove the publication date
- Save the draft
- Navigate to https://127.0.0.1:5000/records/<draft-id>/export/json-ld?preview=1

I will just create an issue out of this

**Comment by utnapischtim** [comment]
would it not be better to use a try except block?

```
try:
    resource_type_id = obj["metadata"]["resource_type"]["id"]
except KeyError:
    return missing
```
or is the "resource_type.id" always there?
the same could be applied to the other changes as well

**Comment by rekt-hard** [comment]
Right - good catch. Not sure about it being there.
In other places something like this is used:  `resource_type_id = py_.get(obj, "metadata.resource_type.id")` (which will return `None` if any intermediate attribute is not available)

Would go for that.

**Review by max-moser — APPROVED** [review]
LGTM
the tests passed locally, and manual testing also showed that it fixes the linked issue

**Pull request merged**
