### PR TITLE
journal: ui serializer formatting improvements

### PR DESCRIPTION
**Pull request by tmorrell**
:heart: Thank you for your contribution!

### Description

This PR includes a number of improvements to how journal metadata is displayed in the UI. I'm kind of touching citation styles here, which is always controversial. My goal is to address inconsistencies between the default citation and "Published In" section, including the following behavior that is odd:

Screenshot 2023-06-22 at 10 43 36 AM

- Issue is at the end of the section, not near volume
- ISSN labeled with "no."
- "pp." appears for both page ranges and article numbers
- Section only appears if a journal title is present (there are no required fields for the journal metadata)
- Full publication date in the middle of the block (this isn't present in Zenodo)
Screenshot 2023-06-22 at 10 35 46 AM
Screenshot 2023-06-22 at 10 36 06 AM

I've tried to use the  default citation style (APA) as much as I could.

Full metadata:
Screenshot 2023-06-22 at 1 06 51 PM

Without ISSN:
Screenshot 2023-06-22 at 1 05 48 PM

Without Issue:
Screenshot 2023-06-22 at 1 07 37 PM

Without Volume:
Screenshot 2023-06-22 at 1 48 59 PM

Without Title:
Screenshot 2023-06-22 at 2 26 28 PM

 

### Checklist

Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:

- [ ] I'm aware of the [code of conduct](https://inveniordm.docs.cern.ch/contribute/code-of-conduct/).
- [ ] I've created [logical separate commits](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#commits) and followed the [commit message format](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#commit-message).
- [ ] I've added relevant test cases.
- [ ] I've added relevant documentation.
- [ ] I've marked [translation strings](https://inveniordm.docs.cern.ch/develop/best-practices/i18n/) (for relevant code).
- [ ] I've followed the [CSS/JS](https://inveniordm.docs.cern.ch/develop/best-practices/css-js/) and [React](https://inveniordm.docs.cern.ch/develop/best-practices/react/) guidelines (for relevant code).
- [ ] I've followed the [web accessibility](https://inveniordm.docs.cern.ch/develop/best-practices/accessibility/) guidelines (for relevant code).
- [ ] I've followed the [user interface](https://inveniordm.docs.cern.ch/develop/best-practices/ui/) guidelines (for relevant code).
- [ ] I've identified the [copyright holder(s)](https://inveniordm.docs.cern.ch/contribute/copyright-policy/) and updated copyright headers for touched files (>15 lines contributions).
- [ ] I've NOT included third-party code (copy/pasted source code or new dependencies).

**Third-party code**

If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).

**Reminder**

By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:

1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license your contribution under the current repository’s license.

### CODE REVIEW

**Review by slint — APPROVED** [review]
LGTM, thanks a lot for having a look at the formatting! In the end, we decided to go with this formatting as the "one and only" (also for Zenodo) and revisit making it configurable in the future (if requested).

One comment/suggestion: in https://github.com/inveniosoftware/invenio-rdm-records/pull/1405, we also tried to integrate the publication date into the string, by [parsing the year part from the EDTF date](https://github.com/inveniosoftware/invenio-rdm-records/pull/1405/files#diff-60d2e985baca9c1e2ddd61f92355612c6707af6901d2242e8d473a726af5cf30R178-R182). Is there a way to integrate this into the formatting suggested in this PR?

**Comment by tmorrell** [comment]
Great! I'll work on adding in the publication date (even though it's technically not in that part of the citation, we agreed it would be a nice addition). It should be a pretty fast addition.

**Comment by kpsherva** [comment]
hello Tom! I hope you don't mind if I add the pub date, we need to finalise this one

**Comment by kpsherva** [comment]
I think you don't allow to push to this branch because I couldn't update, therefore I branched out to https://github.com/inveniosoftware/invenio-rdm-records/pull/1524, (its merge of this PR and https://github.com/inveniosoftware/invenio-rdm-records/pull/1305 
if you agree mine is fine we can close this and #1305

**Comment by lnielsen** [comment]
Merged as part of #1524

**Pull request closed without merging**
