### PR TITLE
identifiers: add pmcid

### PR DESCRIPTION
**Pull request by tmorrell**
:heart: Thank you for your contribution!

### Description

PMCID is a critical identifier for US institutions who need manage NIH compliance. It's already available in idutils, but didn't make it into the default RDM list. PMID did make the list, but unfortunately PMID and PMCID are different identifiers for the metadata and article content respectively. Most articles will have both, and they will be different (see https://pubmed.ncbi.nlm.nih.gov/36092012/).

If we're only supporting one identifier, PMCID would actually be preferred as it's more useful. But it seemed less disruptive to just add PMCID instead of swapping.

### Checklist

Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:

- [ ] I'm aware of the [code of conduct](https://inveniordm.docs.cern.ch/contribute/code-of-conduct/).
- [ ] I've created [logical separate commits](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#commits) and followed the [commit message format](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#commit-message).
- [ ] I've added relevant test cases.
- [ ] I've added relevant documentation.
- [ ] I've marked [translation strings](https://inveniordm.docs.cern.ch/develop/best-practices/i18n/) (for relevant code).
- [ ] I've followed the [CSS/JS](https://inveniordm.docs.cern.ch/develop/best-practices/css-js/) and [React](https://inveniordm.docs.cern.ch/develop/best-practices/react/) guidelines (for relevant code).
- [ ] I've followed the [web accessibility](https://inveniordm.docs.cern.ch/develop/best-practices/accessibility/) guidelines (for relevant code).
- [ ] I've followed the [user interface](https://inveniordm.docs.cern.ch/develop/best-practices/ui/) guidelines (for relevant code).
- [ ] I've identified the [copyright holder(s)](https://inveniordm.docs.cern.ch/contribute/copyright-policy/) and updated copyright headers for touched files (>15 lines contributions).
- [ ] I've NOT included third-party code (copy/pasted source code or new dependencies).

**Third-party code**

If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).

**Reminder**

By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:

1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license your contribution under the current repository’s license.

### CODE REVIEW

**Review by fenekku — APPROVED** [review]
For us this is great (approved!), but it might be worth broaching at some point the discussion of what makes it into the defaults and what doesn't. 

This is a case where it's easy for our institution to add this to our definition of `RDM_RECORDS_IDENTIFIERS_SCHEMES` in our invenio.cfg (as we do with other schemes we've added) and the identifier is US-centric. 
Here it's not a big deal, but I can see in other situations where it can be strange e.g. adding a custom provider/fields in rdm-records when
having them as separate installable packages would be more modular... 

Anyway this works for us :man_shrugging:

**Comment by tmorrell** [comment]
Yup, this isn't so much of a technical pull request as a policy pull request.

**Comment by tmorrell** [comment]
I've done some more testing, and because identifier types are shared between alternative and related this change breaks the DataCite submission pipeline. I'm going to think about better approaches for this.

**Comment by tmorrell** [comment]
I'm closing this for now. There is odd behavior with DOI minting and non-standard identifier types. It looks like there is a validation step that uses non-serialized metadata. I'm tracking the issue https://github.com/caltechlibrary/caltechauthors/issues/6

**Pull request closed without merging**
