### PR TITLE
serializers: add datapackage serializer

### PR DESCRIPTION
**Pull request by roll**
:heart: Thank you for your contribution! (:heart: Thanks for working on the project!)

### Description

[Data Package](https://datapackage.org/) is a European Commission-funded project (via NLnet) that is a standard containing a set of lightweight specifications for describing datasets and individual data files. The standard is widely used for data interoperability in other data portal systems like [CKAN](https://github.com/frictionlessdata/ckanext-datapackage), [Dryad](https://blog.okfn.org/2020/11/18/dryad-and-frictionless-data-collaboration/), [Our World in Data](https://github.com/owid/owid-datasets), and others. The main benefit of adoption the Data Package Standard is a rich set of software for reading and validating datasets - https://datapackage.org/standard/software/ (the most advanced implementations are in Python and R, as well as a Desktop application).

By creating this pull request, we would like to bootstrap a discussion if Invenio RDM (and Zenodo) would consider accepting the `datapackage.json` format to be one of the export targets for datasets' metadata (we also prepared a PR for `invenio-app-rdm` in case this PR is accepted). Also, tagging our friends from the University of California @sdiggs and @sapetti9 from Open Knowledge Foundation.

Thanks a lot in advance!

### Checklist

Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:

- [x] I'm aware of the [code of conduct](https://inveniordm.docs.cern.ch/contribute/code-of-conduct/).
- [x] I've created [logical separate commits](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#commits) and followed the [commit message format](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#commit-message).
- [x] I've added relevant test cases.
- [x] I've added relevant documentation.
- [x] I've marked [translation strings](https://inveniordm.docs.cern.ch/develop/howtos/i18n/).
- [x] I've identified the [copyright holder(s)](https://inveniordm.docs.cern.ch/contribute/copyright-policy/) and updated copyright headers for touched files (>15 lines contributions).
- [x] I've NOT included third-party code (copy/pasted source code or new dependencies).
    * If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).

**Frontend**

- [x] I've followed the [CSS/JS](https://inveniordm.docs.cern.ch/develop/best-practices/css-js/) and [React](https://inveniordm.docs.cern.ch/develop/best-practices/react/) guidelines.
- [x] I've followed the [web accessibility](https://inveniordm.docs.cern.ch/develop/best-practices/accessibility/) guidelines.
- [x] I've followed the [user interface](https://inveniordm.docs.cern.ch/develop/best-practices/ui/) guidelines.

**Reminder**

By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:

1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license your contribution under the current repository’s license.

### CODE REVIEW

**Comment by slint** [comment]
Hi @roll, thank you for opening this PR. The only thing missing to integrate this is hooking it up to our REST API responses to retrieve a record in the Data package serialization format via content negotiation.

Do you know what MIMEType would be appropriate for data packages? E.g. for RO-Crate we're using `application/ld+json;profile="https://w3id.org/ro/crate/1.1"`, so would something like `application/ld+json;profile="https://datapackage.org/profiles/2.0/datapackage.json"` make sense?

If that's fine I can push a commit on top of this PR to finalize this and merge.

**Comment by roll** [comment]
Thanks @slint!

Data Package is closer to the DataCite format but [it hasn't yet gotten](https://github.com/frictionlessdata/datapackage/issues/927) its own MIME-type like `application/vnd.datacite.datacite+json` so I think just plain `application/json` would work the best (similarly to the native platform's JSON format).

Please feel free to update the PR and let me know you need help with anything else :handshake:

**Comment by roll** [comment]
Hi @slint, do you need any help?

Regarding the exporter I think I didn't get it from the initial reply but I have the PR ready for `invenio_add_rdm` as well (if you meant this one):

```
diff --git a/invenio_app_rdm/config.py b/invenio_app_rdm/config.py
index af244486..b354e441 100644
--- a/invenio_app_rdm/config.py
+++ b/invenio_app_rdm/config.py
@@ -751,6 +751,16 @@ APP_RDM_RECORD_EXPORTERS = {
         "content-type": "application/vnd.datacite.datacite+xml",
         "filename": "{id}.xml",
     },
+    # TODO: it requires a `invenio-rdm-recors` version update
+    "datapackage.json": {
+        "name": _("Data Package"),
+        "serializer": (
+            "invenio_rdm_records.resources.serializers:DataPackageSerializer"
+        ),
+        "params": {"options": {"indent": 2, "sort_keys": True}},
+        "content-type": "application/json",
+        "filename": "{id}.datapackage.json",
+    },
     "dublincore": {
         "name": _("Dublin Core XML"),
         "serializer": (
```

cc @sapetti9

**Comment by roll** [comment]
Hi @slint, any new on this PR? cc @sdiggs @sapetti9

**Comment by slint** [comment]
Hi @roll, sorry for this going under the radar. I will open a PR to hook-in the serializer to the REST API responses and the one you mentioned in App-RDM as well (will ping you there for a quick check).

**Pull request merged**
