### PR TITLE
notifications: add submission action notifications

### PR DESCRIPTION
**Pull request by rekt-hard**
actions: send notification on submission accept action

:heart: Thank you for your contribution!

### Description

closes https://github.com/inveniosoftware/invenio-requests/issues/339
Send notification when executing a submission request action.

### Checklist

Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:

- [ ] I'm aware of the [code of conduct](https://inveniordm.docs.cern.ch/contribute/code-of-conduct/).
- [ ] I've created [logical separate commits](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#commits) and followed the [commit message format](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#commit-message).
- [ ] I've added relevant test cases.
- [ ] I've added relevant documentation.
- [ ] I've marked [translation strings](https://inveniordm.docs.cern.ch/develop/best-practices/i18n/) (for relevant code).
- [ ] I've followed the [CSS/JS](https://inveniordm.docs.cern.ch/develop/best-practices/css-js/) and [React](https://inveniordm.docs.cern.ch/develop/best-practices/react/) guidelines (for relevant code).
- [ ] I've followed the [web accessibility](https://inveniordm.docs.cern.ch/develop/best-practices/accessibility/) guidelines (for relevant code).
- [ ] I've followed the [user interface](https://inveniordm.docs.cern.ch/develop/best-practices/ui/) guidelines (for relevant code).
- [ ] I've identified the [copyright holder(s)](https://inveniordm.docs.cern.ch/contribute/copyright-policy/) and updated copyright headers for touched files (>15 lines contributions).
- [ ] I've NOT included third-party code (copy/pasted source code or new dependencies).

**Third-party code**

If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).

**Reminder**

By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:

1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license your contribution under the current repository’s license.

### CODE REVIEW

**Comment by rekt-hard** [comment]
Specific accept action notification for the community submission. Other actions will follow a similar pattern. I think accept/decline would be the same. Expire should probably also only notify the request creator (can we resolve the system as executing user?). For cancel, it should probably notify the community owners/curators (similar to the community submission). Most other things can probably stay the same - at least from the current standpoint.

**Review by kpsherva — APPROVED** [review]

**Comment by kpsherva** [comment]
if we merge this PR we will send 2 emails for access request accept action, see:
https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/requests/access/requests.py#L104 
could you integrate (replace) this one with your newly defined actions notifications ?

**Comment by rekt-hard** [comment]
These notifications are specific to the community submission/inclusion actions. Do access requests and inclusion requests share the same service? If not, we should be good here.
Should we create a separate PR for replacing the mails with notifications?

**Comment by kpsherva** [comment]
> These notifications are specific to the community submission/inclusion actions. Do access requests and inclusion requests share the same service? If not, we should be good here. Should we create a separate PR for replacing the mails with notifications?

OK for separate PR!

**Comment by rekt-hard** [comment]
Just tested locally and it did not send two mails/notifications on access request accept action.

**Pull request merged**
